server:
  port: 8081
  servlet:
    context-path: /system
current:
  limiting:
    part-enabled: false
    rule:
      fail-fast: true
      qps: 100
      overflow: true
      initial-delay: 0
    enabled: true
